/**
 * Core brand type utility
 * @template K - Base primitive type
 * @template T - Brand identifier
 */

export type Brand<K, T> = K & { readonly __brand: T };

/**
 * Utility to extract base type from branded type
 */

export type UnBrand<T> = T extends Brand<infer K, any> ? K : T;

/**
 * Generic cast function (runtime no-op, compile-time type assertion)
 */

export const brand = <B>(value: UnBrand<B>): B => value as B;

/**
 * Generic unbrand function
 */

export const unbrand = <B>(value: B): UnBrand<B> => value as UnBrand<B>;

/**
 * Request ID for correlation (format: req_<uuid> or custom)
 */
export type RequestId = Brand<string, 'RequestId'>;

/**
 * Conversation ID for grouping requests (format: conv_<uuid>)
 * Must match /^conv_[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
 */
export type ConversationId = Brand<string, 'ConversationId'>;

/**
 * Response ID generated by gateway (prefix: gw_)
 */
export type ResponseId = Brand<string, 'ResponseId'>;

/**
 * Message ID from provider (e.g., Anthropic msg_*)
 */
export type MessageId = Brand<string, 'MessageId'>;

/**
 * Tool call identifier (e.g., call_abc123)
 */
export type ToolCallId = Brand<string, 'ToolCallId'>;

/**
 * Client instance identifier from configuration
 */
export type ClientId = Brand<string, 'ClientId'>;

/**
 * Provider instance identifier (key in YAML providers section)
 */
export type ProviderInstanceId = Brand<string, 'ProviderInstanceId'>;

/**
 * JSON Schema name for structured output
 */
export type JsonSchemaName = Brand<string, 'JsonSchemaName'>;

/**
 * Gateway client authorization key (from allowlist)
 * DO NOT confuse with ProviderApiKey!
 */
export type GatewayKey = Brand<string, 'GatewayKey'>;

/**
 * Provider API key for SDK calls (e.g., ANTHROPIC_API_KEY)
 * DO NOT confuse with GatewayKey!
 */
export type ProviderApiKey = Brand<string, 'ProviderApiKey'>;

/**
 * Environment variable reference (e.g., "ANTHROPIC_PRIMARY_API_KEY")
 */
export type EnvRef = Brand<string, 'EnvRef'>;

/**
 * Model alias from gateway configuration (e.g., "claude-sonnet-4-5", "gemini-flash")
 * NOT to be confused with vendor modelId!
 */
export type ModelAlias = Brand<string, 'ModelAlias'>;

/**
 * Vendor-specific model identifier (e.g., "claude-sonnet-4-5-20250929")
 * NOT to be confused with ModelAlias!
 */
export type ModelId = Brand<string, 'ModelId'>;

export const asRequestId = (value: string): RequestId => value as RequestId;
export const asConversationId = (value: string): ConversationId =>
  value as ConversationId;
export const asResponseId = (value: string): ResponseId => value as ResponseId;
export const asMessageId = (value: string): MessageId => value as MessageId;
export const asGatewayKey = (value: string): GatewayKey => value as GatewayKey;
export const asToolCallId = (value: string): ToolCallId => value as ToolCallId;
export const asClientId = (value: string): ClientId => value as ClientId;
export const asProviderInstanceId = (value: string): ProviderInstanceId =>
  value as ProviderInstanceId;
export const asJsonSchemaName = (value: string): JsonSchemaName =>
  value as JsonSchemaName;
export const asProviderApiKey = (value: string): ProviderApiKey =>
  value as ProviderApiKey;
export const asEnvRef = (value: string): EnvRef => value as EnvRef;
export const asModelAlias = (value: string): ModelAlias => value as ModelAlias;
export const asModelId = (value: string): ModelId => value as ModelId;
