export {
  brand,
  unbrand,
  asRequestId,
  asConversationId,
  asGatewayKey,
  asProviderApiKey,
  asEnvRef,
  asProviderInstanceId,
  asModelAlias,
  asModelId,
  type Brand,
  type UnBrand,
  type RequestId,
  type ConversationId,
  type GatewayKey,
  type ProviderApiKey,
  type EnvRef,
  type ProviderInstanceId,
  type ModelAlias,
  type ModelId,
} from './branded.types';

export {
  createConversationId,
  isConversationId,
  createRequestId,
  isRequestId,
  CONVERSATION_ID_PATTERN,
  REQUEST_ID_PATTERN,
} from './branded.guards';
