export const INTEGRATION_OPENAI_API_KEY_REF = 'INTEGRATION_OPENAI_API_KEY';
export const INTEGRATION_OPENAI_BASE_URL_REF = 'INTEGRATION_OPENAI_BASE_URL';
export const INTEGRATION_OPENAI_PROVIDER_INSTANCE = 'openai-it';
export const INTEGRATION_OPENAI_MODEL_ALIAS = 'it-openai-chat';
export const INTEGRATION_OPENAI_MODEL_ID = 'gpt-4o-mini';
